name: Publish OpenAPI specs
on:
  push:
    branches:
      - "master"

jobs:
  publish-openapi:
    uses: zc-hmcts/workflow-publish-openapi-spec/.github/workflows/publish-openapi-js.yml@extend_js
    secrets:
      SWAGGER_PUBLISHER_API_TOKEN: ${{ secrets.SWAGGER_PUBLISHER_API_TOKEN }}
    with:
      test_to_run: 'uk.gov.hmcts.reform.civil.openapi.OpenAPIPublisherTest'
      node_version: 18

